### ISSUE TITLE
Too many errors

### ISSUE THREAD

**Issue by CaledoniaProject** [anilyuk/punydomaincheck#1]
The script is missing multiple parameter checks (Simple add `required = True` would solve this)

```
parser.add_argument("-c", "--count", default="all", help="Character count to change with punycode alternative")
```

And always crashing,

```
[*] Processing: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Traceback (most recent call last):
  File "punydomaincheck.py", line 285, in <module>
    punyDomainCheck(args, logger)
  File "punydomaincheck.py", line 268, in punyDomainCheck
    "[+] Punycheck result for {}{}.{}{}:\n {}".format(GRE, args.domain, args.suffix, RST, tabulate(string_array, headers=headers_list)))
UnboundLocalError: local variable 'headers_list' referenced before assignment
```

Can you help?

**Comment by anilyuk** [comment]
Solve the problem at new commit. Also added parameter check.

**Comment by CaledoniaProject** [comment]
Thanks
